 CREATE TABLE users (
      Id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      FirstName VARCHAR(100) NOT NULL,
	  LastName VARCHAR(100) NOT NULL,
	  BirthDay DATE NOT NULL,
	  Gender VARCHAR(10) NOT NULL
   );
